### ISSUE TITLE
excel encrypt output fails when commas or quotes are in values 

### ISSUE THREAD

**Issue by kzollove** [TuftsCTSI/csv2xlsx#1]
For example, will split a value "last name, first name" in column "name" into two columns

Should be fixed by using a a CSV library. Apache commons csv is one option:

https://simplesolution.dev/top-3-libraries-for-writing-and-reading-csv-file-in-java/

**Comment by xitology** [comment]
See https://github.com/TuftsCTSI/TRDW.jl/pull/60

**Comment by clarkevans** [comment]
This is now integrated into TRDW.jl but to use in the encrypt function, you would need to add this boilerplate:

```
    using JavaCall
    JavaCall.isloaded() ? nothing : JavaCall.init()
    JavaCall.assertroottask_or_goodenv()
```

and to the Makefile, add `JULIA_COPY_STACKS=1` before `julia`.

An updated Makefile is at https://github.com/TuftsCTSI/TRDW-Guides/blob/main/Makefile
